sudo: required
before_install:
  - sudo add-apt-repository ppa:george-edison55/precise-backports --yes
  - sudo apt-get update
  - sudo apt-get install libpng-dev libjpeg-dev libxxf86vm1 libxxf86vm-dev libxi-dev libxrandr-dev
  - sudo apt-get install mesa-common-dev
  - sudo apt-get install mesa-utils-extra libgl1-mesa-dev libglapi-mesa
  - sudo apt-get install libao-dev
  - sudo apt-get install libcurl4-openssl-dev
  
# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - g++
  
install:
  # - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  # - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  
  - sudo apt-get install cmake
   
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="http://www.cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    fi
  
  # Go to the Root directory  
  # - cd ..

# Build steps
script: ./scripts/cmake-make.sh -j8
